version: '3.8' # Указываем версию синтаксиса Compose

services:
  # Название сервиса (можешь придумать свое)
  telegram-bot:
    # Инструкция для сборки образа:
    image: romanvivchar7/zenhealingbot:latest
    # Имя контейнера (необязательно, но удобно)
    container_name: zenhealing_telegram_bot_container
    # Политика перезапуска:
    # 'always' - всегда перезапускать, даже после перезагрузки сервера
    # 'unless-stopped' - перезапускать, если не остановлен вручную
    restart: unless-stopped
    # Файл, из которого нужно загрузить переменные окружения в контейнер
    # Docker Compose прочитает твой .env файл и передаст переменные внутрь контейнера
    env_file:
      - .env
    # Проброс портов: <порт_на_хосте>:<порт_в_контейнере>
    # Пробрасываем порт 8080 из контейнера (WEBAPP_PORT) на порт 8080
    # хост-машины, но делаем его доступным ТОЛЬКО локально (127.0.0.1).
    # Это важно для безопасности, чтобы только Nginx мог достучаться до бота.
    # Замени 8080 на свой WEBAPP_PORT, если он другой.
    ports:
      - '127.0.0.1:8080:8080'
    # Опционально: Настройка логирования (пример)
    logging:
      driver: 'json-file'
      options:
        max-size: '10m' # Максимальный размер лог-файла
        max-file: '3' # Количество хранимых лог-файлов
